debug = true # 是否启用调试
runtime = "runtime" # 运行文件目录

[server]
addr = ":9000" # 监听地址
baseUrl = "http://api.example.com" # 最终部署后访问该服务的地址

# 数据库配置
[db]
driver = "mysql" # 数据库驱动，可选项 sqlite3 | mysql
uri = "" # 数据库地址

# redis 配置
[redis]
cluster = false # 是否集群
addrs = [] # 如果是集群，将集群地址都写到数组内，如果不是集群，只写一个元素
password = ""
db = 1
namespace = "api" # 前缀