[server]
addr = "0.0.0.0:9001"
debug = true

[cors]
origin = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
headers = ["Content-Length", "Content-Type", "Origin"]
credentials = true
maxAge = 24 # 单位: 小时

[db]
type = "sqlite3"
uri = "api.db"
autoMigrate = false

[log]
level = "info"
format = "console"
path = "logs/api.log"
simplify = true
debug = false